# SPDX-FileCopyrightText: © 2026 Shaun Wilson
# SPDX-License-Identifier: MIT

from __future__ import annotations

from cryptography.hazmat.primitives import serialization
from punit import collections, fact
from reshut.jwk import (
    ECJWK,
    JWK,
    OctetJWK,
    OKPJWK,
    RSAJWK,
)
from reshut.jwk.utils import (
    from_private_key,
    from_public_key,
    from_symmetric_key,
    to_private_key,
    to_public_key,
    to_symmetric_key,
)
from reshut.utils import keygen
from reshut import Algorithm
from typing import cast


@fact
def test_symmetric_key_conversion() -> None:
    """A symmetric key generated by ``from_symmetric_key`` must be recoverable via ``to_symmetric_key``."""
    secret: bytes = b'super-secret-key'
    jwk = from_symmetric_key(Algorithm.HS256, secret, key_id='sym-1')
    recovered: bytes = to_symmetric_key(jwk)
    assert recovered == secret, 'Symmetric key round-trip failed.'


@fact
def test_rsa_key_roundtrip() -> None:
    """RSA private/public keys must survive a full JWK round-trip."""
    rsa_jwk: JWK = keygen(Algorithm.RS256)
    # ``keygen`` returns a private JWK - convert to a private key object and back
    private_key = to_private_key(cast(RSAJWK, rsa_jwk))
    regenerated_jwk: JWK = from_private_key(Algorithm.RS256, private_key)
    # the regenerated JWK must contain the same modulus and exponent
    original_modulus: str = cast(RSAJWK, rsa_jwk)['n']
    regenerated_modulus: str = cast(RSAJWK, regenerated_jwk)['n']
    original_exponent: str = cast(RSAJWK, rsa_jwk)['e']
    regenerated_exponent: str = cast(RSAJWK, regenerated_jwk)['e']
    assert original_modulus == regenerated_modulus, 'RSA modulus mismatch after round-trip.'
    assert original_exponent == regenerated_exponent, 'RSA exponent mismatch after round-trip.'


@fact
def test_ec_key_roundtrip() -> None:
    """EC private/public keys must survive a full JWK round-trip."""
    ec_jwk: JWK = keygen(Algorithm.ES256)
    private_key = to_private_key(cast(ECJWK, ec_jwk))
    regenerated_jwk: JWK = from_private_key(Algorithm.ES256, private_key)
    # Compare curve, x and y coordinates
    original_curve: str = cast(ECJWK, ec_jwk)['crv']
    regenerated_curve: str = cast(ECJWK, regenerated_jwk)['crv']
    assert original_curve == regenerated_curve, 'EC curve mismatch after round-trip.'
    assert cast(ECJWK, ec_jwk)['x'] == cast(ECJWK, regenerated_jwk)['x'], 'EC x-coordinate mismatch.'
    assert cast(ECJWK, ec_jwk)['y'] == cast(ECJWK, regenerated_jwk)['y'], 'EC y-coordinate mismatch.'


@fact
def test_ed25519_key_roundtrip() -> None:
    """Ed25519 private/public keys must survive a full JWK round-trip."""
    ed_jwk: JWK = keygen(Algorithm.ED25519)
    private_key = to_private_key(cast(OKPJWK, ed_jwk))
    regenerated_jwk: JWK = from_private_key(Algorithm.ED25519, private_key)
    assert cast(OKPJWK, ed_jwk)['x'] == cast(OKPJWK, regenerated_jwk)['x'], 'Ed25519 public key mismatch.'
    assert cast(OKPJWK, ed_jwk)['d'] == cast(OKPJWK, regenerated_jwk)['d'], 'Ed25519 private key mismatch.'


@fact
def test_ed448_key_roundtrip() -> None:
    """Ed448 private/public keys must survive a full JWK round-trip."""
    ed_jwk: JWK = keygen(Algorithm.ED448)
    private_key = to_private_key(cast(OKPJWK, ed_jwk))
    regenerated_jwk: JWK = from_private_key(Algorithm.ED448, private_key)
    assert cast(OKPJWK, ed_jwk)['x'] == cast(OKPJWK, regenerated_jwk)['x'], 'Ed448 public key mismatch.'
    assert cast(OKPJWK, ed_jwk)['d'] == cast(OKPJWK, regenerated_jwk)['d'], 'Ed448 private key mismatch.'


@fact
def test_public_key_conversion_rsa() -> None:
    """A public RSA JWK generated from a private key must be recoverable via ``to_public_key``."""
    private_jwk: JWK = keygen(Algorithm.RS512)
    public_jwk: JWK = from_public_key(Algorithm.RS512, to_private_key(cast(RSAJWK, private_jwk)).public_key())
    public_key = to_public_key(public_jwk)
    # Verify that the public key matches the one derived from the private key
    original_pub = to_private_key(cast(RSAJWK, private_jwk)).public_key()
    assert collections.areSame(
        public_key.public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.PKCS1),
        original_pub.public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.PKCS1)
    )


@fact
def test_public_key_conversion_ec() -> None:
    """A public EC JWK generated from a private key must be recoverable via ``to_public_key``."""
    private_jwk: JWK = keygen(Algorithm.ES384)
    public_jwk: JWK = from_public_key(Algorithm.ES384, to_private_key(cast(ECJWK, private_jwk)).public_key())
    public_key = to_public_key(public_jwk)
    original_pub = to_private_key(cast(ECJWK, private_jwk)).public_key()
    assert collections.areSame(
        public_key.public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo),
        original_pub.public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo)
    )


@fact
def test_public_key_conversion_okp() -> None:
    """A public OKP JWK (Ed25519) generated from a private key must be recoverable via ``to_public_key``."""
    private_jwk: JWK = keygen(Algorithm.ED25519)
    org_pubkey = to_private_key(cast(OKPJWK, private_jwk)).public_key()
    public_jwk: JWK = from_public_key(Algorithm.ED25519, org_pubkey)
    public_key = to_public_key(public_jwk)
    original_pub = to_private_key(cast(OKPJWK, private_jwk)).public_key()
    
    assert collections.areSame(
        public_key.public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw),
        original_pub.public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    )
