#!/bin/bash
# SPDX-FileCopyrightText: © 2026 Shaun Wilson
# SPDX-License-Identifier: MIT
##
#
# this script exists for CI/CD
#
##
set -eo pipefail
if [ -z "$VIRTUAL_ENV" ]; then
    source .venv/bin/activate
fi
sed "s/0.0.0/$SEMVER/g" --in-place pyproject.toml
sed "s/0.0.0/$SEMVER/g" --in-place src/reshut/__init__.py
sed "s/0abc123/$(git rev-parse --short HEAD)/g" --in-place src/reshut/__init__.py
rm -rf build/
rm -rf dist/
rm -rf src/*.egg-info/
python3 -m build
