#!/bin/bash
# SPDX-FileCopyrightText: © 2026 Shaun Wilson
# SPDX-License-Identifier: MIT
##
#
# this script exists for CI/CD
#
# this script can also be used to prep a local shell/environment:
#
# source .scripts/init-venv
#
##
set -euo pipefail

# resolve
SCRIPT_DIR=$(dirname $(realpath "${BASH_SOURCE[0]}"))
SRC_DIR=$(realpath "$SCRIPT_DIR/../src")
WORKSPACE_NAME=$(basename `dirname "$SRC_DIR"`)

# initialize
if [ ! -z "$(which deactivate)" ]; then
    echo "..deactivating current venv"
    deactivate
fi
if [ ! -d ".venv" ]; then
    "python${PYTHON_VERSION:-3}" -m venv --prompt "$WORKSPACE_NAME" .venv
fi

# activate
#export PS1='\$ '
echo -n -e "\033]0;$WORKSPACE_NAME\007"
source .venv/bin/activate

# tools and deps
pip install --upgrade pip
pip install pip-tools
pip-compile -o requirements.txt --all-extras --strip-extras pyproject.toml
if [ -f requirements.txt ]; then
    pip install -r requirements.txt
fi
export PYTHONPATH="$SRC_DIR"
export MYPYPATH="$SRC_DIR"
if ! [[ ":PATH:" == *":$SCRIPT_DIR:"* ]]; then
    export PATH="$SCRIPT_DIR:$PATH"
fi
