#!/usr/bin/env python
# SPDX-FileCopyrightText: © 2026 Shaun Wilson
# SPDX-License-Identifier: MIT
##
from subprocess import run
from sys import executable, argv, exit
result = run([executable, '-m', 'reshut', 'tokenize'] + argv[1:], check=False)
exit(result.returncode)
